### ISSUE TITLE
Сборка сервера

### ISSUE THREAD

**Issue by artemziborev** [kmlebedev/txmlconnector#1]
Добрый день! Интересен ваш проект. К сожалению не могу скомпилировать сервер или запустить его в докере.
Буду очень признателен если вы добавите в репозиторий собранный exe-файл сервера. Спасибо!)

**Comment by kmlebedev** [comment]
> Добрый день! Интересен ваш проект. К сожалению не могу скомпилировать сервер или запустить его в докере.
> Буду очень признателен если вы добавите в репозиторий собранный exe-файл сервера. Спасибо!)

А что не получилось ?
Если что exe файл есть внутри докер образа

**Comment by artemziborev** [comment]
Докер контейнер тоже не запускается (OS Ubuntu)

при компиляции main.go сервера падает со следующей ошибкой
goroutine 1 [running]:
syscall.(*LazyProc).mustFind(...)
	C:/Program Files/Go/src/syscall/dll_windows.go:322
syscall.(*LazyProc).Call(0xc0001893e0, 0xc00019e110, 0x2, 0x2, 0xc0000d9db8, 0x1, 0x1, 0x100000000000000)
	C:/Program Files/Go/src/syscall/dll_windows.go:338 +0xc7
main.init.0()

**Comment by artemziborev** [comment]
➜  ~ docker run kmlebedev/txmlconnector server
wine: created the configuration directory '/root/.wine'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0014:err:ole:get_local_server_stream Failed: 800736b7
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
wine: configuration in L"/root/.wine" has been updated.
0009:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-06-24T09:42:14Z" level=info msg="Initialize module: /usr/bin/txmlconnector64-6.19.2.21.8.dll"
InitCrashHandler: Z:\usr\bin\txmlconnector-server-210624-094214.mdmp
time="2021-06-24T09:42:14Z" level=panic msg="Initialize error: Insufficient buffer."
panic: (*logrus.Entry) 0xc0001de2a0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001de1c0, 0x0, 0xc000136330, 0x26)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x5ae
github.com/sirupsen/logrus.(*Entry).Log(0xc0001de1c0, 0xc000000000, 0xc000113e08, 0x2, 0x2)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0xc5
github.com/sirupsen/logrus.(*Logger).Log(0xc0001de150, 0xc000000000, 0xc000113e08, 0x2, 0x2)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:198 +0xab
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:247
github.com/sirupsen/logrus.Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:129
main.init.0()
	/go/src/github.com/kmlebedev/txmlconnector/server/main.go:84 +0x9d1
[2021-06-24 09:42:14.904620] [0x00000009] [info]    Failed to initialize library: ��������� ���� �� ����������


это ошибка запуска докера

**Comment by kmlebedev** [comment]
> это ошибка запуска докера

посмотреть exe нормальный, а под ubuntu wine кривой

**Comment by artemziborev** [comment]
а где взять нормальный exe? докер не запускается и я не могу оттуда файл взять

а под какой ос нормальный wine?

**Comment by artemziborev** [comment]
если можно, напишите на почту telikt@mail.ru
или телегам @bonuseventus

**Comment by kmlebedev** [comment]
образ пофиксил
