### ISSUE TITLE
типы данных в Clickhouse

### ISSUE THREAD

**Issue by nableru** [kmlebedev/txmlconnector#10]
Большое спасибо за проект, Консантин.

В ходе изучения возник вопрос почему в examples/clickhouse-exporter для таблиц БД выбраны именно такие типы данных?
Например, для securities.secid UInt16, хотя согласно документации https://www.finam.ru/files/htt/TXmlConnector_20201208.pdf тип значения в XML - integer

Извините, если вопрос дилетантский, но в моем окружении этот нюанс (на самом деле их несколько) приводит к ошибке: "clickhouse [AppendRow]: secid clickhouse [AppendRow]: converting int to UInt16 is unsupported"

**Comment by kmlebedev** [comment]
Я обновил драйвер клика на нативный и пошли аналогичный ошибки, при Append нужно приводить типы к табличным смотри комит https://github.com/kmlebedev/txmlconnector/commit/3e82cfb44674fb0d98e5a506abf07e96d1101059. Взял UInt16 так как это необходимо и достаточно(диапазон от 0 до 65535), так что бы одна строчка меньше места на диске занимала.
Как картинке самый старший secid 29234 по торгам T+2

<img width="1141" alt="Снимок экрана 2023-03-18 в 02 24 54" src="https://user-images.githubusercontent.com/9497591/226058421-cb683413-cdea-49e8-b613-0ceec61fd724.png">
