### ISSUE TITLE
Изменить наименование версий на vX.X.X

### ISSUE THREAD

**Issue by sukamenev** [kmlebedev/txmlconnector#14]
Иначе сайт pkg.go.dev не видит обновлений пакета.
Сейчас показывает последнюю версию вашего пакета v0.0.6.

**Comment by kmlebedev** [comment]
Done

**Comment by sukamenev** [comment]
Ничего не изменилось. Нужно не просто название на 1.0.26 сменить, а реально метку такую поставить.

https://pkg.go.dev/github.com/kmlebedev/txmlconnector

**Comment by sukamenev** [comment]
Сейчас у нового релиза стоит тэг v0.26. И поэтому ничего не поменялось. Не грузит go свежуб версию пакета.

**Comment by brkly** [comment]
> Сейчас у нового релиза стоит тэг v0.26. И поэтому ничего не поменялось. Не грузит go свежуб версию пакета.

+1
