### ISSUE TITLE
Хотелось бы увидеть примеры сообщений и ответов на них или ссылку на какой-то пример

### ISSUE THREAD

**Issue by sukamenev** [kmlebedev/txmlconnector#16]
* Как выставлять и отменять заявку
* Как получать уведомление о выполненной/частично выполненной заявке
* Как смотреть портфель

Сейчас есть только пример сообщения для коннекта. Этого ну совсем мало.

Может где-то есть документация на это? ТОгда хотелось бы ссылку на неё.

**Comment by kmlebedev** [comment]
Есть руководство пользователя по api
https://files.comon.ru/usercontent/TXmlConnector.pdf

**Comment by sukamenev** [comment]
Спасибо!
Пожалуйста, добавьте эту ссылку в список ссылок.

**Comment by kmlebedev** [comment]
done
