### ISSUE TITLE
Windows 10 Ошибка в запуске сервера в докере

### ISSUE THREAD

**Issue by Nikolay-D** [kmlebedev/txmlconnector#2]
Константин, спасибо, что готовы поделиться своим продуктом и потратить свое время.
Пожалуйста, подскажите направление, в какую сторону копать. В Докере и Го я - ноль.

Windows 10 x64, 
Установил FreeType через freetype-2.3.5-1-setup.exe.

Пробую запустить образ в докере. Клиент ошибок не выдает.
При запуске сервера получаю:

wine: created the configuration directory '/root/.wine'
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-085312.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-101900.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-102015.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-102253.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-103032.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-103537.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-123245.mdmp

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-125431.mdmp

or equal to 2.0.5.
http://www.freetype.org
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0050:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0050:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x800736b7
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b7
0050:err:ole:apartment_get_local_server_stream Failed: 0x800736b7
0050:err:ole:start_rpcss Failed to open RpcSs service
0050:err:seh:call_stack_handlers invalid frame 00007FFDF1320028 (0000000000122000-0000000000220000)
0050:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
0040:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0040:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0040:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
0040:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0040:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0060:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0060:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0060:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0060:err:seh:call_stack_handlers invalid frame 00007FFE31E05778 (0000000000122000-0000000000220000)
0060:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
0024:err:environ:run_wineboot boot event wait timed out
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T08:53:12Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
time="2021-07-03T08:53:12Z" level=info msg="Server running ..."
0078:fixme:ver:GetCurrentPackageId (00000000277FFE10 0000000000000000): stub
time="2021-07-03T08:53:12Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFDC40DB698 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T10:19:00Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T10:19:00Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000278FFE10 0000000000000000): stub
time="2021-07-03T10:19:00Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFDD70F0198 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T10:20:15Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T10:20:15Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000275FFE10 0000000000000000): stub
time="2021-07-03T10:20:15Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFC8BBDA488 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T10:22:53Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T10:22:53Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000277FFE10 0000000000000000): stub
time="2021-07-03T10:22:53Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFC80BC6788 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T10:30:32Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0058:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0058:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T10:30:32Z" level=info msg="Server running ..."
0068:fixme:ver:GetCurrentPackageId (00000000277FFE10 0000000000000000): stub
time="2021-07-03T10:30:32Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFE64E20DF8 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T10:35:37Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T10:35:37Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000275FFE10 0000000000000000): stub
time="2021-07-03T10:35:37Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFCDFA36478 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T12:32:45Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T12:32:45Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000276FFE10 0000000000000000): stub
time="2021-07-03T12:32:45Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002c:err:seh:call_stack_handlers invalid frame 00007FFCCB8869E8 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
time="2021-07-03T12:54:31Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0054:err:ole:start_rpcss Failed to open RpcSs service
time="2021-07-03T12:54:31Z" level=info msg="Server running ..."
0064:fixme:ver:GetCurrentPackageId (00000000277FFE10 0000000000000000): stub
time="2021-07-03T12:54:31Z" level=info msg="Press CRTL+C to stop the server..."
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

002c:err:seh:call_stack_handlers invalid frame 00007FFC2B8C8EC8 (0000000000122000-0000000000220000)
002c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub

time="2021-07-03T13:05:58Z" level=info msg="Initialize module: txmlconnector64-6.19.2.21.8.dll"

0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

0054:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".

0054:err:ole:start_rpcss Failed to open RpcSs service

InitCrashHandler: Z:\usr\bin\txmlconnector-server-210703-130558.mdmp

time="2021-07-03T13:05:58Z" level=info msg="Server running ..."

0064:fixme:ver:GetCurrentPackageId (00000000275FFE10 0000000000000000): stub

time="2021-07-03T13:05:58Z" level=info msg="Press CRTL+C to stop the server..."

**Comment by kmlebedev** [comment]
Да такое бывает при первом запуске, при втором запуске ругаться уже не будет и появиться только строка 
`time="2021-07-03T13:05:58Z" level=info msg="Press CRTL+C to stop the server..."`
Попробую при сборке первый запуск осуществить, что бы не пугало

**Comment by kmlebedev** [comment]
Если на винде локально хочется запускать то докер вообще не нужен, можно 
я могу собрать чуть позже добавить бинари сервера, а команды можно отправлять через https://habr.com/ru/company/vdsina/blog/563872/

**Comment by Nikolay-D** [comment]
> Если на винде локально хочется запускать то докер вообще не нужен, можно
я могу собрать чуть позже добавить бинари сервер

Буду ждать, спасибо

**Comment by kmlebedev** [comment]
@Nikolay-D С ходу не получилось собрать, но после фикса go-release-action`а https://github.com/wangyoucao577/go-release-action/issues/38 завелось 

https://github.com/kmlebedev/txmlconnector/releases/download/v0.20/windows_amd64.zip

**Comment by kmlebedev** [comment]
Теперь релизы содержат бинарники под винду https://github.com/kmlebedev/txmlconnector/releases
под линукс току мало, так как нужен docker c wine
