### ISSUE TITLE
InitCrashHandler после Initialize

### ISSUE THREAD

**Issue by leeroy-Jk** [kmlebedev/txmlconnector#7]
Константин, здравствуйте. Подскажите, вы знаете природу возникновения такой ошибки/предупреждения после вызова `Initialize()`: `InitCrashHandler: <path_to_.mdmp>`?

Встречал я ее и в вашем варианте реализации, и в своем, который писал на С++ на windows. Поддержка transaq connector говорит, что это может быть проблема с кодировкой передаваемого xml. Но какой бы вариант настроек самой windows не использовался мной, это сообщение все равно появляется

**Comment by kmlebedev** [comment]
@fenixD3 Нужно больше контекста, что делаете. Такую ошибку не встречал. Была ошибка инициализации из-за отсутствия папки `logs` после какой то версии, так как она раньше создавалась dll-ко самостоятельно, а теперь необходимо создавать самим приложением перед инициализацией.

**Comment by mobile-systems** [comment]
> [@fenixD3](https://github.com/fenixD3) Нужно больше контекста, что делаете. Такую ошибку не встречал. Была ошибка инициализации из-за отсутствия папки `logs` после какой то версии, так как она раньше создавалась dll-ко самостоятельно, а теперь необходимо создавать самим приложением перед инициализацией.

Спасибо ОГРОМНОЕ за подсказку, второй день бьюсь, не мог понять что за проблема такая, сначала же всё работало, а после перестало, оказалось случайно удалил директорию LOGS.
