### ISSUE TITLE
Ошибка в ответе на команду get_max_buy_sell

### ISSUE THREAD

**Issue by falkolab** [kmlebedev/txmlconnector#8]
Добрый день! 

В ответ на команду get_max_buy_sell получаю ответ:

`<max_buy_sell client="4LW39/4LW39 union="649933RBO1T"></max_buy_sell>`

Обратите внимание на закрывающую кавычку атрибута client.

Выдержки из лога клиентской библиотеки

```
204848.495856 [0032] [clbk] <info> [O] [1270u] <server_status sys_ver="631" build="12" server_tz="Russian Standard Time" id="6" connected="true"/>
...
204959.828445 [0032] [0308] <cmd> [I] <command id="get_max_buy_sell" client="4LW39/4LW39" union="649933RBO1T"><security><board>TQBR</board><seccode>SBER</seccode></security></command>
205000.158445 [0032] [clbk] <info> [O] [990u] <max_buy_sell client="4LW39/4LW39 union="649933RBO1T"></max_buy_sell>
```
Ответ поддержки finam:
```
Добрый день!

Возьмите версию по ссылке
https://files.comon.ru/usercontent/TXmlConnector.zip

В ней возвращается корректно:

103018.142612 [12472] [11748] <cmd> [I] <command id="get_max_buy_sell" client="0G3TV/0G3TV" union="126471R1P8Y"><security><board>TQBR</board><seccode>SBER</seccode></security></command>
103018.143608 [12472] [11748] <res> [R] <result success="true"/>
103018.163554 [12472] [clbk] <info> [O] [20066u] <max_buy_sell client="0G3TV/0G3TV" union="126471R1P8Y"></max_buy_sell>

 
С уважением,
Александр Абрамов,

```

Не затруднит ли вас обновить бибилиотеку и контейнер на github?

**Comment by falkolab** [comment]
Я вижу что у вас в проекте Версия: 2.21.16 и по ссылке та же https://www.finam.ru/howtotrade/soft/tconnector/
Но может они пофиксили без изменения версии, md5 по их и вашему файлу разные.

**Comment by kmlebedev** [comment]
@falkolab Добрый день, 

> Я вижу что у вас в проекте Версия: 2.21.16 и по ссылке та же https://www.finam.ru/howtotrade/soft/tconnector/ Но может они пофиксили без изменения версии, md5 по их и вашему файлу разные.

Добрый день, кажется версии разные сейчас проверяю, можно без обновления образа самостоятельно обновлять dll 
через перепенные `TC_DLL_PATH`  и `TC_DLL_VER`

**Comment by falkolab** [comment]
Спасибо. Да но не хотелось менять конфиги.

**Comment by kmlebedev** [comment]
> falkolab

Да по ссылке версия 2.21.21, а на сейте финама 2.21.16
```
144703.473462 [0032] [0036] <info> Open log logs, level 2
144703.474299 [0032] [0036] <info> System version 6.31. TXmlConnector version 2.21.21
144703.474389 [0032] [0036] <info> Initializing...
 
```

**Comment by kmlebedev** [comment]
> Спасибо. Да но не хотелось менять конфиги.

Готово. `docker pull kmlebedev/txmlconnector:6.19.2.21.21`
